alter table "public"."Discipline" drop constraint "Discipline_competition_fkey";

create table "public"."AgeGroup" (
    "id" bigint generated by default as identity not null,
    "code" text not null,
    "name" text not null,
    "official" boolean not null
);


alter table "public"."AgeGroup" enable row level security;

create table "public"."CompetitionDiscipline" (
    "disciplineName" text not null,
    "competition" bigint not null,
    "discipline" bigint,
    "ageGroup" bigint not null
);


alter table "public"."CompetitionDiscipline" enable row level security;

create table "public"."Country" (
    "id" bigint generated by default as identity not null,
    "code" text not null,
    "name" text not null
);


alter table "public"."Country" enable row level security;

create table "public"."Federation" (
    "id" bigint generated by default as identity not null,
    "code" text not null,
    "name" text not null
);


alter table "public"."Federation" enable row level security;

alter table "public"."Athlete" alter column "firstname" set data type text using "firstname"::text;

alter table "public"."Athlete" alter column "lastname" set data type text using "lastname"::text;

alter table "public"."Competition" alter column "email" set data type text using "email"::text;

alter table "public"."Competition" alter column "host" set data type text using "host"::text;

alter table "public"."Competition" alter column "lv" drop not null;

alter table "public"."Competition" alter column "lv" set data type bigint using "lv"::bigint;

alter table "public"."Competition" alter column "name" set data type text using "name"::text;

alter table "public"."Competition" alter column "organizer" set data type text using "organizer"::text;

alter table "public"."Competition" alter column "venue" set data type text using "venue"::text;

alter table "public"."Discipline" drop column "ageGroup";

alter table "public"."Discipline" drop column "competition";

alter table "public"."Discipline" drop column "discipline";

alter table "public"."Discipline" add column "code" text not null;

alter table "public"."Discipline" add column "id" bigint generated by default as identity not null;

alter table "public"."Discipline" add column "name" text not null;

alter table "public"."Discipline" add column "official" boolean not null;

alter table "public"."Entry" alter column "ageGroup" set data type text using "ageGroup"::text;

alter table "public"."Entry" alter column "discipline" set data type text using "discipline"::text;

alter table "public"."Location" alter column "country" set data type bigint using "country"::bigint;

alter table "public"."Location" alter column "lv" drop not null;

alter table "public"."Location" alter column "lv" set data type bigint using "lv"::bigint;

alter table "public"."Location" alter column "name" set data type text using "name"::text;

CREATE UNIQUE INDEX "AgeGroup_code_key" ON public."AgeGroup" USING btree (code);

CREATE UNIQUE INDEX "AgeGroup_pkey" ON public."Discipline" USING btree (id);

CREATE UNIQUE INDEX "AgeGroup_pkey1" ON public."AgeGroup" USING btree (id);

CREATE UNIQUE INDEX "Country_code_key" ON public."Country" USING btree (code);

CREATE UNIQUE INDEX "Country_name_key" ON public."Country" USING btree (name);

CREATE UNIQUE INDEX "Country_pkey" ON public."Country" USING btree (id);

CREATE UNIQUE INDEX "Discipline_code_key" ON public."Discipline" USING btree (code);

CREATE UNIQUE INDEX "Federation_pkey" ON public."Federation" USING btree (id);

alter table "public"."AgeGroup" add constraint "AgeGroup_pkey1" PRIMARY KEY using index "AgeGroup_pkey1";

alter table "public"."Country" add constraint "Country_pkey" PRIMARY KEY using index "Country_pkey";

alter table "public"."Discipline" add constraint "AgeGroup_pkey" PRIMARY KEY using index "AgeGroup_pkey";

alter table "public"."Federation" add constraint "Federation_pkey" PRIMARY KEY using index "Federation_pkey";

alter table "public"."AgeGroup" add constraint "AgeGroup_code_key" UNIQUE using index "AgeGroup_code_key";

alter table "public"."Competition" add constraint "Competition_lv_fkey" FOREIGN KEY (lv) REFERENCES "Federation"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Competition" validate constraint "Competition_lv_fkey";

alter table "public"."CompetitionDiscipline" add constraint "CompetitionDiscipline_ageGroup_fkey" FOREIGN KEY ("ageGroup") REFERENCES "AgeGroup"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."CompetitionDiscipline" validate constraint "CompetitionDiscipline_ageGroup_fkey";

alter table "public"."CompetitionDiscipline" add constraint "CompetitionDiscipline_discipline_fkey" FOREIGN KEY (discipline) REFERENCES "Discipline"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."CompetitionDiscipline" validate constraint "CompetitionDiscipline_discipline_fkey";

alter table "public"."CompetitionDiscipline" add constraint "Discipline_competition_fkey" FOREIGN KEY (competition) REFERENCES "Competition"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."CompetitionDiscipline" validate constraint "Discipline_competition_fkey";

alter table "public"."Country" add constraint "Country_code_key" UNIQUE using index "Country_code_key";

alter table "public"."Country" add constraint "Country_name_key" UNIQUE using index "Country_name_key";

alter table "public"."Discipline" add constraint "Discipline_code_key" UNIQUE using index "Discipline_code_key";

alter table "public"."Location" add constraint "Location_country_fkey" FOREIGN KEY (country) REFERENCES "Country"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Location" validate constraint "Location_country_fkey";

alter table "public"."Location" add constraint "Location_lv_fkey" FOREIGN KEY (lv) REFERENCES "Federation"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Location" validate constraint "Location_lv_fkey";

grant delete on table "public"."AgeGroup" to "anon";

grant insert on table "public"."AgeGroup" to "anon";

grant references on table "public"."AgeGroup" to "anon";

grant select on table "public"."AgeGroup" to "anon";

grant trigger on table "public"."AgeGroup" to "anon";

grant truncate on table "public"."AgeGroup" to "anon";

grant update on table "public"."AgeGroup" to "anon";

grant delete on table "public"."AgeGroup" to "authenticated";

grant insert on table "public"."AgeGroup" to "authenticated";

grant references on table "public"."AgeGroup" to "authenticated";

grant select on table "public"."AgeGroup" to "authenticated";

grant trigger on table "public"."AgeGroup" to "authenticated";

grant truncate on table "public"."AgeGroup" to "authenticated";

grant update on table "public"."AgeGroup" to "authenticated";

grant delete on table "public"."AgeGroup" to "service_role";

grant insert on table "public"."AgeGroup" to "service_role";

grant references on table "public"."AgeGroup" to "service_role";

grant select on table "public"."AgeGroup" to "service_role";

grant trigger on table "public"."AgeGroup" to "service_role";

grant truncate on table "public"."AgeGroup" to "service_role";

grant update on table "public"."AgeGroup" to "service_role";

grant delete on table "public"."CompetitionDiscipline" to "anon";

grant insert on table "public"."CompetitionDiscipline" to "anon";

grant references on table "public"."CompetitionDiscipline" to "anon";

grant select on table "public"."CompetitionDiscipline" to "anon";

grant trigger on table "public"."CompetitionDiscipline" to "anon";

grant truncate on table "public"."CompetitionDiscipline" to "anon";

grant update on table "public"."CompetitionDiscipline" to "anon";

grant delete on table "public"."CompetitionDiscipline" to "authenticated";

grant insert on table "public"."CompetitionDiscipline" to "authenticated";

grant references on table "public"."CompetitionDiscipline" to "authenticated";

grant select on table "public"."CompetitionDiscipline" to "authenticated";

grant trigger on table "public"."CompetitionDiscipline" to "authenticated";

grant truncate on table "public"."CompetitionDiscipline" to "authenticated";

grant update on table "public"."CompetitionDiscipline" to "authenticated";

grant delete on table "public"."CompetitionDiscipline" to "service_role";

grant insert on table "public"."CompetitionDiscipline" to "service_role";

grant references on table "public"."CompetitionDiscipline" to "service_role";

grant select on table "public"."CompetitionDiscipline" to "service_role";

grant trigger on table "public"."CompetitionDiscipline" to "service_role";

grant truncate on table "public"."CompetitionDiscipline" to "service_role";

grant update on table "public"."CompetitionDiscipline" to "service_role";

grant delete on table "public"."Country" to "anon";

grant insert on table "public"."Country" to "anon";

grant references on table "public"."Country" to "anon";

grant select on table "public"."Country" to "anon";

grant trigger on table "public"."Country" to "anon";

grant truncate on table "public"."Country" to "anon";

grant update on table "public"."Country" to "anon";

grant delete on table "public"."Country" to "authenticated";

grant insert on table "public"."Country" to "authenticated";

grant references on table "public"."Country" to "authenticated";

grant select on table "public"."Country" to "authenticated";

grant trigger on table "public"."Country" to "authenticated";

grant truncate on table "public"."Country" to "authenticated";

grant update on table "public"."Country" to "authenticated";

grant delete on table "public"."Country" to "service_role";

grant insert on table "public"."Country" to "service_role";

grant references on table "public"."Country" to "service_role";

grant select on table "public"."Country" to "service_role";

grant trigger on table "public"."Country" to "service_role";

grant truncate on table "public"."Country" to "service_role";

grant update on table "public"."Country" to "service_role";

grant delete on table "public"."Federation" to "anon";

grant insert on table "public"."Federation" to "anon";

grant references on table "public"."Federation" to "anon";

grant select on table "public"."Federation" to "anon";

grant trigger on table "public"."Federation" to "anon";

grant truncate on table "public"."Federation" to "anon";

grant update on table "public"."Federation" to "anon";

grant delete on table "public"."Federation" to "authenticated";

grant insert on table "public"."Federation" to "authenticated";

grant references on table "public"."Federation" to "authenticated";

grant select on table "public"."Federation" to "authenticated";

grant trigger on table "public"."Federation" to "authenticated";

grant truncate on table "public"."Federation" to "authenticated";

grant update on table "public"."Federation" to "authenticated";

grant delete on table "public"."Federation" to "service_role";

grant insert on table "public"."Federation" to "service_role";

grant references on table "public"."Federation" to "service_role";

grant select on table "public"."Federation" to "service_role";

grant trigger on table "public"."Federation" to "service_role";

grant truncate on table "public"."Federation" to "service_role";

grant update on table "public"."Federation" to "service_role";

create policy "Enable read access for all users"
on "public"."AgeGroup"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."CompetitionDiscipline"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."Country"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."Federation"
as permissive
for select
to public
using (true);



