

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Athlete" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "firstname" character varying NOT NULL,
    "lastname" character varying NOT NULL,
    "birthyear" numeric
);


ALTER TABLE "public"."Athlete" OWNER TO "postgres";


ALTER TABLE "public"."Athlete" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Athlete_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Competition" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "venue" character varying NOT NULL,
    "date" "date" NOT NULL,
    "host" character varying NOT NULL,
    "organizer" character varying NOT NULL,
    "canceled" boolean NOT NULL,
    "email" character varying NOT NULL,
    "location" bigint NOT NULL,
    "lv" character varying NOT NULL,
    "entryDeadline" "date" NOT NULL
);


ALTER TABLE "public"."Competition" OWNER TO "postgres";


ALTER TABLE "public"."Competition" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Competition_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Discipline" (
    "discipline" character varying NOT NULL,
    "ageGroup" character varying NOT NULL,
    "competition" bigint NOT NULL
);


ALTER TABLE "public"."Discipline" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Entry" (
    "id" bigint NOT NULL,
    "athlete" bigint NOT NULL,
    "competition" bigint NOT NULL,
    "discipline" character varying NOT NULL,
    "disciplineLong" character varying NOT NULL
);


ALTER TABLE "public"."Entry" OWNER TO "postgres";


ALTER TABLE "public"."Entry" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Location" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "lv" character varying NOT NULL,
    "country" character varying NOT NULL,
    "lat" numeric NOT NULL,
    "lng" numeric
);


ALTER TABLE "public"."Location" OWNER TO "postgres";


ALTER TABLE "public"."Location" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Location_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Athlete"
    ADD CONSTRAINT "Athlete_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Competition"
    ADD CONSTRAINT "Competition_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Entry"
    ADD CONSTRAINT "Entry_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Location"
    ADD CONSTRAINT "Location_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Competition"
    ADD CONSTRAINT "Competition_location_fkey" FOREIGN KEY ("location") REFERENCES "public"."Location"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Discipline"
    ADD CONSTRAINT "Discipline_competition_fkey" FOREIGN KEY ("competition") REFERENCES "public"."Competition"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Entry"
    ADD CONSTRAINT "Entry_athlete_fkey" FOREIGN KEY ("athlete") REFERENCES "public"."Athlete"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Entry"
    ADD CONSTRAINT "Entry_competition_fkey" FOREIGN KEY ("competition") REFERENCES "public"."Competition"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."Athlete" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Competition" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Discipline" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Entry" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Location" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


















































































































































































































GRANT ALL ON TABLE "public"."Athlete" TO "anon";
GRANT ALL ON TABLE "public"."Athlete" TO "authenticated";
GRANT ALL ON TABLE "public"."Athlete" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Athlete_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Athlete_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Athlete_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Competition" TO "anon";
GRANT ALL ON TABLE "public"."Competition" TO "authenticated";
GRANT ALL ON TABLE "public"."Competition" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Competition_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Competition_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Competition_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Discipline" TO "anon";
GRANT ALL ON TABLE "public"."Discipline" TO "authenticated";
GRANT ALL ON TABLE "public"."Discipline" TO "service_role";



GRANT ALL ON TABLE "public"."Entry" TO "anon";
GRANT ALL ON TABLE "public"."Entry" TO "authenticated";
GRANT ALL ON TABLE "public"."Entry" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Location" TO "anon";
GRANT ALL ON TABLE "public"."Location" TO "authenticated";
GRANT ALL ON TABLE "public"."Location" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Location_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Location_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Location_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
