name: Deploy Migrations to Production
on:
  push:
    paths:
      - prisma/migrations/**
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        working-directory: ./backend
        run: npm install
      - name: Apply all pending migrations to the database
        working-directory: ./backend
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DB_URL }}
          DIRECT_URL: ${{ secrets.PRODUCTION_DB_URL }}